# SPDX-License-Identifier: GPL-2.0

# Minimal System
obj-y += clk/
obj-y += pinctrl/
obj-y += uart/
obj-y += timer/

# Basic System
obj-y += dma/
obj-y += rtc/
obj-y += dumpreg/
obj-y += watchdog/
obj-y += iommu/
obj-y += mbus/

# Storage
obj-y += mmc/
obj-y += redeposit/

# Graphics
obj-y += video/
obj-y += g2d/
obj-y += di/

# Multi-Media
obj-y += ve/

# Security
obj-y += ce/
obj-y += smc/
obj-y += sid/

# I/O Connectivity
obj-y += gmac/
obj-y += usb/
obj-y += twi/
obj-y += spi/
obj-y += spi-ng/
obj-y += pwm/

# Wireless
obj-y += net/
obj-y += bluetooth/

# Power Management
obj-y += irqchip/
obj-y += standby/
obj-y += thermal/
obj-y += nvmem/
obj-y += pm_domain/
obj-y += power/
obj-y += cpufreq/

# AMP/XPU
obj-y += msgbox/
obj-y += hwspinlock/
obj-y += remoteproc/
obj-y += rpmsg/
obj-y += rpbuf/
obj-y += npu/

# Misc
obj-y += misc/

# pstore
obj-y += pstore/