subdir-ccflags-y += -I$(obj)/include/hal
subdir-ccflags-y += -I$(obj)/include/drv
subdir-ccflags-y += -I$(obj)/include/osal
subdir-ccflags-y += -I$(obj)/include/hal/sdmmc

obj-y += drv/
obj-y += rtos-hal/hal/
obj-y += osal/
obj-y += test/
