
# compile static lib
ifeq ($(MPPCFG_COMPILE_STATIC_LIB), Y)
CONFIG_COMPILE_STATIC_LIB := y
else
CONFIG_COMPILE_STATIC_LIB := n
endif

# choose format of vdecoder
ifeq ($(CONFIG_COMPILE_STATIC_LIB), y)

    LOCAL_CFLAGS += -DCONFIG_COMPILE_STATIC_LIB

    LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_H264
    LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_H265
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_MJPEGPLUS
    LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_MJPEG
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_AVS
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_MPEG2
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_MPEG4BASE
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_MPEG4DIVX311
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_MPEG4H263
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_MPEG4NORMAL
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_MPEG4VP6
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_RV
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_VP6SOFT
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_VP8
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_VP9HW
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_VP9SOFT
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_WMV3
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_WMV12SOFT
    #LOCAL_CFLAGS += -DCONFIG_ENABLE_DECODER_H265SOFT
endif
