PRODUCT_PACKAGES += \
	cedarx.conf \
	liblive555 \
	librtp \
	libadecoder \
	libadecoder_for_debug \
	libaw_rw_data_api \
	libaw_aacdec \
	libaw_alacdec \
	libaw_amrdec \
	libaw_apedec \
	libaw_dsddec \
	libaw_flacdec \
	libaw_g729dec \
	libaw_mp3dec \
	libaw_oggdec \
	libaw_wavdec \
	libaw_opusdec \
	libaw_atrcdec \
	libaw_cookdec \
	libaw_radec \
	libaw_siprdec \
	libsubdecoder \
	libaencoder \
