obj-${CONFIG_SUBSYS_MULTI_CONSOLE} += multi_console/
obj-$(CONFIG_COMPONENTS_RPBUF) += rpbuf/
obj-$(CONFIG_DRIVER_SYSCONFIG) += script_config/
obj-$(CONFIG_VIRT_LOG) += virt_log/
obj-$(CONFIG_KALLSYMS) += kallsyms/
