subdir-ccflags-y += -I$(srctree)/ekernel/drivers/include/  \
                    -I$(srctree)/ekernel/components/aw/mmap\

obj-$(CONFIG_SUNXI_PWM_TEST) += test_pwm.o
obj-$(CONFIG_SUNXI_GPIO_TEST) += test_gpio.o
obj-$(CONFIG_SUNXI_TWI_TEST) += test_twi.o
obj-$(CONFIG_SUNXI_UART_TEST) += test_uart.o
obj-$(CONFIG_SUNXI_STANDBY_TEST) += test_standby.o
