obj-y += cpuport.o
obj-y += port.o
obj-$(CONFIG_MELIS_GENERATE_HEAD) += epos_hdr.o
obj-y += exception.o
obj-y += misa.o
obj-y += clocksource.o
obj-y += timer.o
obj-$(CONFIG_DEBUG_BACKTRACE) += backtrace.o
