ccflags-y += 	-I$(obj)/ \
		-I$(srctree)/include/melis/kernel/drivers

obj-y += clk.o
obj-y += clk_factors.o
obj-y += clk_periph.o

obj-$(CONFIG_SOC_SUN8IW21P1) += sun8iw21p1/
obj-$(CONFIG_SOC_SUN20IW3) += sun8iw21p1/
