#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FTS)   += focaltech_ts.o

focaltech_ts-objs		+= focaltech_core.o

focaltech_ts-objs               +=  focaltech_ex_fun.o
focaltech_ts-objs               +=  focaltech_ex_mode.o
focaltech_ts-objs               +=  focaltech_flash.o
focaltech_ts-objs               +=  focaltech_gesture.o
focaltech_ts-objs               +=  focaltech_esdcheck.o
focaltech_ts-objs               +=  focaltech_i2c.o
focaltech_ts-objs               +=  focaltech_sensor.o
focaltech_ts-objs               +=  focaltech_point_report_check.o

focaltech_ts-objs += focaltech_flash/focaltech_upgrade_ft5x46.o
focaltech_ts-objs += focaltech_flash/focaltech_upgrade_ft5822.o
focaltech_ts-objs += focaltech_flash/focaltech_upgrade_ft6336gu.o
focaltech_ts-objs += focaltech_flash/focaltech_upgrade_ft8006.o
focaltech_ts-objs += focaltech_flash/focaltech_upgrade_ft8606.o
focaltech_ts-objs += focaltech_flash/focaltech_upgrade_ft8607.o
focaltech_ts-objs += focaltech_flash/focaltech_upgrade_ft8716.o
focaltech_ts-objs += focaltech_flash/focaltech_upgrade_ft8736.o
focaltech_ts-objs += focaltech_flash/focaltech_upgrade_idc.o
focaltech_ts-objs += focaltech_flash/focaltech_upgrade_test.o

focaltech_ts-objs += focaltech_test/src/focaltech_test.o
focaltech_ts-objs += focaltech_test/src/focaltech_test_main.o
focaltech_ts-objs += focaltech_test/src/focaltech_test_ini.o
focaltech_ts-objs += focaltech_test/src/focaltech_test_global.o
focaltech_ts-objs += focaltech_test/src/focaltech_test_detail_threshold.o
focaltech_ts-objs += focaltech_test/src/focaltech_ic_table.o

focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft3d47.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft3d47.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft8716.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft8716.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft8607.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft8607.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft5x46.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft5x46.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft6x36.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft6x36.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft5822.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft5822.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft8006.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft8006.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft8736.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft8736.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_fte716.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_fte716.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft8606.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft8606.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_config_ft3c47.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_ft3c47.o
focaltech_ts-objs += focaltech_test/supported_ic/focaltech_test_supported_ic.o
