
obj-y += phy/build_nand_partition.o \
	phy/build_phy_partition.o \
	phy/nand_info_init.o \
	physic/nand_format.o \
	physic/nand_id.o \
	physic/nand_phy.o \
	physic/nand_physic_interface_spinand.o \
	physic/nand_scan.o \
	physic/spic_op.o \
	physic/spinand0/spi_nand0.o \
	physic/spinand1/spi_nand1.o \
	physic/spinand2/spi_nand2.o \
	physic/spinand3/spi_nand3.o \
	physic/uboot_tail_spinand.o \
	physic_common/nand_physic_interface.o \
	physic_common/uboot_tail.o \
	physic_common/nand_secure_storage.o \
	physic_v2/chip/nand_chip_common.o \
	physic_v2/chip/nand_chip_function.o \
	physic_v2/chip/nand_chip_interface.o \
	physic_v2/chip/nand_super_chip_common.o \
	physic_v2/chip/nand_super_chip_function.o \
	physic_v2/chip/nand_super_chip_interface.o \
	physic_v2/controller/nand_controller.o \
	physic_v2/controller/nand_controller_common.o \
	physic_v2/controller/nand_controller_op.o \
	physic_v2/hynix16nm/nand1_chip_for_boot.o \
	physic_v2/hynix16nm_4G/nand8_chip_for_boot.o \
	physic_v2/hynix20nm/nand2_chip_for_boot.o \
	physic_v2/hynix26nm/nand3_chip_for_boot.o \
	physic_v2/nand_id2.o \
	physic_v2/nand_phy_init.o \
	physic_v2/nand_physic_interface_rawnand.o \
	physic_v2/nand_platform_data.o \
	physic_v2/uboot_tail_rawnand.o \
	physic_v2/universal/nand0_chip_for_boot.o \
	physic_v2/universal/nand0_chip_op.o \
	physic_v2/universal/nand0_super_chip_op.o \
	physic_v2/version.o \
	phy_v2/build_phy_partition_v2.o \
	phy_v2/nand_info_init_v2.o


