subdir-ccflags-y += -I$(srctree)/ekernel/filesystem/include
subdir-ccflags-y += -I$(srctree)/ekernel/core/rt-thread/include
subdir-ccflags-y += -I$(srctree)/ekernel/components
subdir-ccflags-y += -I$(srctree)/ekernel/components/thirdparty/dfs/include
subdir-ccflags-y += -I$(srctree)/ekernel/components/finsh_cli
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/include/osal
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/include/hal
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/include/drv

obj-y += aw/
obj-y += thirdparty/
