/*
 * Copyright (c) 2008-2016 Allwinner Technology Co. Ltd.
 * All rights reserved.
 *
 * File : CdxISOLang.c
 * Description : iso639 standard for language names
 * History :
 *
 */

#include <CdxISOLang.h>

const Cdx_ISO_639_Lang_t CDX_ISO_639_LANGS[] = {
    { "Afar",                           "aa", "aar", "aar" },
    { "Abkhazian",                      "ab", "abk", "abk" },
    { "Afrikaans",                      "af", "afr", "afr" },
    { "Albanian",                       "sq", "sqi", "alb" },
    { "Amharic",                        "am", "amh", "amh" },
    { "Arabic",                         "ar", "ara", "ara" },
    { "Armenian",                       "hy", "hye", "arm" },
    { "Assamese",                       "as", "asm", "asm" },
    { "Avestan",                        "ae", "ave", "ave" },
    { "Aymara",                         "ay", "aym", "aym" },
    { "Azerbaijani",                    "az", "aze", "aze" },
    { "Bashkir",                        "ba", "bak", "bak" },
    { "Basque",                         "eu", "eus", "baq" },
    { "Belarusian",                     "be", "bel", "bel" },
    { "Bengali",                        "bn", "ben", "ben" },
    { "Bihari",                         "bh", "bih", "bih" },
    { "Bislama",                        "bi", "bis", "bis" },
    { "Bosnian",                        "bs", "bos", "bos" },
    { "Breton",                         "br", "bre", "bre" },
    { "Bulgarian",                      "bg", "bul", "bul" },
    { "Burmese",                        "my", "mya", "bur" },
    { "Catalan",                        "ca", "cat", "cat" },
    { "Chamorro",                       "ch", "cha", "cha" },
    { "Chechen",                        "ce", "che", "che" },
    { "Chinese",                        "zh", "zho", "chi" },
    { "Church Slavic",                  "cu", "chu", "chu" },
    { "Chuvash",                        "cv", "chv", "chv" },
    { "Cornish",                        "kw", "cor", "cor" },
    { "Corsican",                       "co", "cos", "cos" },
    { "Czech",                          "cs", "ces", "cze" },
    { "Danish",                         "da", "dan", "dan" },
    { "Dutch",                          "nl", "nld", "dut" },
    { "Dzongkha",                       "dz", "dzo", "dzo" },
    { "English",                        "en", "eng", "eng" },
    { "Esperanto",                      "eo", "epo", "epo" },
    { "Estonian",                       "et", "est", "est" },
    { "Faroese",                        "fo", "fao", "fao" },
    { "Fijian",                         "fj", "fij", "fij" },
    { "Finnish",                        "fi", "fin", "fin" },
    { "French",                         "fr", "fra", "fre" },
    { "Frisian",                        "fy", "fry", "fry" },
    { "Georgian",                       "ka", "kat", "geo" },
    { "German",                         "de", "deu", "ger" },
    { "Gaelic (Scots)",                 "gd", "gla", "gla" },
    { "Irish",                          "ga", "gle", "gle" },
    { "Gallegan",                       "gl", "glg", "glg" },
    { "Manx",                           "gv", "glv", "glv" },
    { "Greek, Modern",                  "el", "gre", "ell" },
    { "Guarani",                        "gn", "grn", "grn" },
    { "Gujarati",                       "gu", "guj", "guj" },
    { "Hebrew",                         "he", "heb", "heb" },
    { "Herero",                         "hz", "her", "her" },
    { "Hindi",                          "hi", "hin", "hin" },
    { "Hiri Motu",                      "ho", "hmo", "hmo" },
    { "Hungarian",                      "hu", "hun", "hun" },
    { "Icelandic",                      "is", "isl", "ice" },
    { "Inuktitut",                      "iu", "iku", "iku" },
    { "Interlingue",                    "ie", "ile", "ile" },
    { "Interlingua",                    "ia", "ina", "ina" },
    { "Indonesian",                     "id", "ind", "ind" },
    { "Inupiaq",                        "ik", "ipk", "ipk" },
    { "Italian",                        "it", "ita", "ita" },
    { "Javanese",                       "jv", "jaw", "jav" },
    { "Japanese",                       "ja", "jpn", "jpn" },
    { "Greenlandic, Kalaallisut",       "kl", "kal", "kal" },
    { "Kannada",                        "kn", "kan", "kan" },
    { "Kashmiri",                       "ks", "kas", "kas" },
    { "Kazakh",                         "kk", "kaz", "kaz" },
    { "Khmer",                          "km", "khm", "khm" },
    { "Kikuyu",                         "ki", "kik", "kik" },
    { "Kinyarwanda",                    "rw", "kin", "kin" },
    { "Kirghiz",                        "ky", "kir", "kir" },
    { "Komi",                           "kv", "kom", "kom" },
    { "Korean",                         "ko", "kor", "kor" },
    { "Kuanyama",                       "kj", "kua", "kua" },
    { "Kurdish",                        "ku", "kur", "kur" },
    { "Lao",                            "lo", "lao", "lao" },
    { "Latin",                          "la", "lat", "lat" },
    { "Latvian",                        "lv", "lav", "lav" },
    { "Lingala",                        "ln", "lin", "lin" },
    { "Lithuanian",                     "lt", "lit", "lit" },
    { "Letzeburgesch",                  "lb", "ltz", "ltz" },
    { "Macedonian",                     "mk", "mkd", "mac" },
    { "Marshall",                       "mh", "mah", "mah" },
    { "Malayalam",                      "ml", "mal", "mal" },
    { "Maori",                          "mi", "mri", "mao" },
    { "Marathi",                        "mr", "mar", "mar" },
    { "Malay",                          "ms", "msa", "may" },
    { "Malagasy",                       "mg", "mlg", "mlg" },
    { "Maltese",                        "mt", "mlt", "mlt" },
    { "Moldavian",                      "mo", "mol", "mol" },
    { "Mongolian",                      "mn", "mon", "mon" },
    { "Nauru",                          "na", "nau", "nau" },
    { "Navajo",                         "nv", "nav", "nav" },
    { "Ndebele, South",                 "nr", "nbl", "nbl" },
    { "Ndebele, North",                 "nd", "nde", "nde" },
    { "Ndonga",                         "ng", "ndo", "ndo" },
    { "Nepali",                         "ne", "nep", "nep" },
    { "Norwegian",                      "no", "nor", "nor" },
    { "Norwegian Nynorsk",              "nn", "nno", "nno" },
    { "Norwegian Bokmaal",              "nb", "nob", "nob" },
    { "Chichewa; Nyanja",               "ny", "nya", "nya" },
    { "Occitan; Provençal",             "oc", "oci", "oci" },
    { "Oriya",                          "or", "ori", "ori" },
    { "Oromo",                          "om", "orm", "orm" },
    { "On Screen Display",              "od", "osd", "osd" },
    { "Ossetian; Ossetic",              "os", "oss", "oss" },
    { "Panjabi",                        "pa", "pan", "pan" },
    { "Persian",                        "fa", "fas", "per" },
    { "Pali",                           "pi", "pli", "pli" },
    { "Polish",                         "pl", "pol", "pol" },
    { "Portuguese",                     "pt", "por", "por" },
    { "Pushto",                         "ps", "pus", "pus" },
    { "Quechua",                        "qu", "que", "que" },
    { "Original audio",                 "",   "qaa", "qaa" },
    { "Raeto-Romance",                  "rm", "roh", "roh" },
    { "Romanian",                       "ro", "ron", "rum" },
    { "Rundi",                          "rn", "run", "run" },
    { "Russian",                        "ru", "rus", "rus" },
    { "Sango",                          "sg", "sag", "sag" },
    { "Sanskrit",                       "sa", "san", "san" },
    { "Serbian",                        "sr", "srp", "scc" },
    { "Croatian",                       "hr", "hrv", "scr" },
    { "Sinhalese",                      "si", "sin", "sin" },
    { "Slovak",                         "sk", "slk", "slo" },
    { "Slovenian",                      "sl", "slv", "slv" },
    { "Northern Sami",                  "se", "sme", "sme" },
    { "Samoan",                         "sm", "smo", "smo" },
    { "Shona",                          "sn", "sna", "sna" },
    { "Sindhi",                         "sd", "snd", "snd" },
    { "Somali",                         "so", "som", "som" },
    { "Sotho, Southern",                "st", "sot", "sot" },
    { "Spanish",                        "es", "spa", "spa" },
    { "Sardinian",                      "sc", "srd", "srd" },
    { "Swati",                          "ss", "ssw", "ssw" },
    { "Sundanese",                      "su", "sun", "sun" },
    { "Swahili",                        "sw", "swa", "swa" },
    { "Swedish",                        "sv", "swe", "swe" },
    { "Tahitian",                       "ty", "tah", "tah" },
    { "Tamil",                          "ta", "tam", "tam" },
    { "Tatar",                          "tt", "tat", "tat" },
    { "Telugu",                         "te", "tel", "tel" },
    { "Tajik",                          "tg", "tgk", "tgk" },
    { "Tagalog",                        "tl", "tgl", "tgl" },
    { "Thai",                           "th", "tha", "tha" },
    { "Tibetan",                        "bo", "bod", "tib" },
    { "Tigrinya",                       "ti", "tir", "tir" },
    { "Tonga (Tonga Islands)",          "to", "ton", "ton" },
    { "Tswana",                         "tn", "tsn", "tsn" },
    { "Tsonga",                         "ts", "tso", "tso" },
    { "Turkish",                        "tr", "tur", "tur" },
    { "Turkmen",                        "tk", "tuk", "tuk" },
    { "Twi",                            "tw", "twi", "twi" },
    { "Uighur",                         "ug", "uig", "uig" },
    { "Ukrainian",                      "uk", "ukr", "ukr" },
    { "Urdu",                           "ur", "urd", "urd" },
    { "Uzbek",                          "uz", "uzb", "uzb" },
    { "Vietnamese",                     "vi", "vie", "vie" },
    { "Volapuk",                        "vo", "vol", "vol" },
    { "Welsh",                          "cy", "cym", "wel" },
    { "Wolof",                          "wo", "wol", "wol" },
    { "Xhosa",                          "xh", "xho", "xho" },
    { "Yiddish",                        "yi", "yid", "yid" },
    { "Yoruba",                         "yo", "yor", "yor" },
    { "Zhuang",                         "za", "zha", "zha" },
    { "Zulu",                           "zu", "zul", "zul" },
    { 0,                                "",   "",    "" }
};
