#ifndef __SSV_CONF_PARSER_H__
#define __SSV_CONF_PARSER_H__
char const *conf_parser[] = {
"CONFIG_SSV_SUPPORT_ANDROID",
"CONFIG_FW_ALIGNMENT_CHECK",
"CONFIG_PLATFORM_SDIO_OUTPUT_TIMING_3",
"__CHECK_ENDIAN__",
"DEBUG",
"SSV_SUPPORT_SSV6020",
"CONFIG_SSV6200_CLI_ENABLE",
"CONFIG_SSV_BUILD_AS_ONE_KO",
"CONFIG_SSV6200_HAS_RX_WORKQUEUE",
"USE_THREAD_RX",
"USE_GENERIC_DECI_TBL",
"SSV6200_ECO",
"CONFIG_SSV_CTL",
"CONFIG_SSV_SMARTLINK",
"HWIF_SDIO_RX_IRQ",
"CONFIG_FW_ALIGNMENT_CHECK",
"CONFIG_STA_BCN_FILTER",
"CONFIG_SDIO_FAVOR_RX",
"CONFIG_HW_SCAN",
"SSV_SUPPORT_SSV6020B",
"CONFIG_BLE_HCI_BUS_1",
""};
#endif // __SSV_CONF_PARSER_H__
