NOSTDINC_FLAGS := -I$(srctree)/drivers/net/wireless/xr819s/include/

obj-$(CONFIG_XR819S_WLAN) += umac/
obj-$(CONFIG_XR819S_WLAN) += wlan/
obj-$(CONFIG_XR819S_WLAN) += wireless_switch/

clean-files += Module.symvers Module.markers modules modules.order
