ccflags-y += 	-I$(srctree)/include/melis/kernel/rtos/zephyr \
		-I$(srctree)/include/melis/kernel/rtos/zephyr/arch \
	 	-I$(srctree)/ekernel/core/zephyr/kernel/include \
		-I$(srctree)/include/melis/kernel/rtos/zephyr/arch/arm/cortex_m

obj-y += scheduler.o
obj-y += workqueue.o
obj-y += priority.o
obj-y += mutextest.o
obj-y += sched_priority.o
obj-y += timeslice_lock.o
obj-y += preempt_sched.o
