obj-y += sunxi_input.o
obj-$(CONFIG_PLAN_BEETLES) += keyboard/
obj-$(CONFIG_DRIVERS_IR) += ir/
obj-$(CONFIG_DRIVERS_CIR) += rc/
obj-$(CONFIG_DRV_RTP) += rtp/
obj-$(CONFIG_PLAN_SPRITE) += tpadc_keyborad/
obj-$(CONFIG_RTP_SECLET) += tpadc_rtp/
obj-$(CONFIG_CTP_SECLET) += ctp/
