/****************************************************************************
 *   Generated by ACUITY 6.0.14
 *
 *   Neural Network appliction pre-process header file
 ****************************************************************************/
#ifndef _VNN_PRE_PROCESS_H_
#define _VNN_PRE_PROCESS_H_

typedef enum _vnn_file_type
{
    NN_FILE_NONE,
    NN_FILE_TENSOR,
    NN_FILE_QTENSOR,
    NN_FILE_JPG,
    NN_FILE_BINARY
} vnn_file_type_e;

vip_status_e vnn_CreateInOutBufPrepareNetwork(vip_network_items *network_items);

vip_status_e vnn_SetNetworkInOut(vip_network_items *network_items);

unsigned int load_file(const char *name, void *dst);

unsigned int get_file_size(const char *name);

#endif
