# SPDX-License-Identifier: GPL-2.0
# Core
ccflags-y += -I $(srctree)/drivers/pinctrl
obj-$(CONFIG_AW_PINCTRL)			+= pinctrl-sunxi.o
obj-$(CONFIG_AW_PINCTRL_DEBUGFS)		+= pinctrl-debugfs.o
obj-$(CONFIG_AW_PINCTRL_LEDS)			+= pinctrl-leds.o

obj-$(CONFIG_AW_PINCTRL_SUN8IW20)		+= pinctrl-sun8iw20.o
obj-$(CONFIG_AW_PINCTRL_SUN8IW21)		+= pinctrl-sun8iw21.o