# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_RPBUF) += rpbuf_core.o
obj-$(CONFIG_RPBUF_DEV) += rpbuf_dev.o
obj-$(CONFIG_RPBUF_CONTROLLER_SUNXI) += rpbuf_controller_sunxi.o
obj-$(CONFIG_RPBUF_SERVICE_RPMSG) += rpbuf_service_rpmsg.o
obj-$(CONFIG_RPBUF_SAMPLE_SUNXI) += rpbuf_sample_sunxi.o
