subdir-ccflags-y += -I$(srctree)/ekernel/core/rt-thread/include
obj-${CONFIG_DRIVER_GPIO}           += gpio/
obj-${CONFIG_DRIVER_DMA}            += dma/
obj-$(CONFIG_DRIVER_SERIAL)         += serial/
obj-${CONFIG_DRIVER_TWIBUS}         += twi/
obj-${CONFIG_DRIVER_SPIBUS}         += spi/
obj-${CONFIG_DRIVER_PWM}            += pwm/
obj-${CONFIG_DRIVER_CCMU}           += ccmu/
