obj-$(CONFIG_SND_SUNXI_SOC_AUDIOCODEC) += sun8iw8_sndcodec_new.o
obj-$(CONFIG_SND_SUNXI_SOC_AUDIOCODEC) += sunxi_sndcodec.o
obj-$(CONFIG_SND_SUNXI_SOC_AUDIOCODEC) += sunxi_codec.o
obj-$(CONFIG_SND_SUNXI_SOC_AUDIOCODEC) += sunxi_codecdma.o
obj-$(CONFIG_SND_SUNXI_SOC_SUN8IW8_DAUDIO) += sun8iw8-snddaudio0.o
obj-$(CONFIG_SND_SUNXI_SOC_SUN8IW8_DAUDIO) += bb_dai.o
